config/routes.rb
WebAlerts::Application.routes.draw do

  devise_for :users

  resources :home, only: :index

  resources :alerts, only: [ :index, :new, :create, :destroy ]

  resources :locations, only: :show

  root 'home#index'
  
end

app/models/alert.rb
class Alert < ActiveRecord::Base

	OFFER_TYPES = { 'Offering' => 'offering', 'Wanted' => 'wanted' }
  
	PRICE_TYPES = { 
    'Fixed Price' => 'fixed', 
    'Negotiable' => 'negotiable', 
    'Free' => 'free',
    'Swap/Trade' => 'swap-trade'
  }

  BASE_URL = 'http://www.gumtree.com.au'

  belongs_to :user, inverse_of: :alerts
  belongs_to :category
  belongs_to :location
  has_many :alert_items, inverse_of: :alert, dependent: :delete_all

  before_save :clean_keyword!

  validates :user_id, presence: true
  validates :name, length: { minimum: 3, maximum: 300 }
  validates :keyword, length: { maximum: 300 }

  validates :radius, inclusion: { in: Location::RADIUS_KMS }
  
  validates :min_price, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
  validates :max_price, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
  
  validates :offer_type, inclusion: { in: OFFER_TYPES.values, message: "%{value} is not a valid offer type" }, allow_blank: true
  validates :price_type, inclusion: { in: PRICE_TYPES.values, message: "%{value} is not a valid price type" }, allow_blank: true

  validate :category_valid
  validate :price_range_valid
  validate :last_run_date_valid

  def offer_type_str
  	return OFFER_TYPES.invert[self.offer_type]
  end

	def price_type_str
  	return PRICE_TYPES.invert[self.price_type]
  end

  def last_run_str
    if self.last_run
      self.last_run.in_time_zone.to_s(:aus_datetime).squeeze(' ').strip
    else
      ''
    end
  end

  def location_str
    location_name = location.blank? ? 'Anywhere' : location.name
    return "#{radius}km of #{location_name}"
  end

  def description
    str = keyword.blank? ? 'Anything' : "'#{keyword}'"
    str += ' in '
    str += category.blank? ? 'all categories' : "'#{category.name}'"
    str += ' from '
    str += min_price.blank? ? '$0' : '$%.2f' % min_price
    str += ' to '
    str += max_price.blank? ? 'infinity' : '$%.2f' % max_price
    str += " within #{location_str}"
    
    str += ", #{offer_type_str}" unless offer_type.blank?
    str += ", #{price_type_str}" unless price_type.blank?

    return str
  end

  def url
    save if changed?
    filters = filter_hash
    
    if category.blank? && keyword.blank?

      if filters.empty?
        if location.blank?
          url = '/'  # empty search
        else
          url = "/s-#{location.url_path}/#{location_url_str}"  # empty search with location
        end

      else
        url = "/s-ads"  # filters only
        url += "/#{location_url_str}" unless location.blank?  # filters and location
      end

    elsif category.blank?
      url = "/s-#{location.url_path}/#{url_keyword}/k0#{location_url_str}"  # keyword only

    elsif keyword.blank?
      url = "/s-#{category.url_path}#{location.url_path}/c#{category.ref}#{location_url_str}"  # category only

    else
      url = "/s-#{category.url_path}/#{location.url_path}/#{url_keyword}/k0c#{category.ref}#{location_url_str}"  # category and keyword
    end

    url += "?#{filters.to_query}" unless filters.empty?

    return url
  end

  private

  def category_valid
    unless self.category_id.blank?
      unless Category.exists?(self.category_id)
        errors.add(:category_id, "doesn't exist")
      end
    end
  end

  def price_range_valid
    unless self.min_price.blank? || self.max_price.blank?
      if self.max_price < self.min_price
        errors.add(:min_price, "is greater than the maximum price")
      end
    end
  end

  def last_run_date_valid
    if self.last_run      
      if self.last_run > DateTime.now
        errors.add(:last_run, "can't be in the future")
      end
    end

    if !self.new_record?
      previous_value = Alert.find(self.id).last_run

      if previous_value
        if !self.last_run
          errors.add(:last_run, "value can't be replaced with nil")

        elsif previous_value > self.last_run
          errors.add(:last_run, "can't be before the previous value")
        end
      end

    end
  end

  # removes non-alphanumeric/space and multiple spaces
  def clean_keyword!
    unless self.keyword.blank?
      self.keyword = self.keyword.squeeze(' ').strip.gsub(/[^\da-z ]/i, '')
    end
  end

  # returns the price range for url
  def price_range_str
    if min_price.blank? && max_price.blank?
      return nil
    else
      return "#{min_price}__#{max_price}"
    end
  end

  def location_url_str
    return location.blank? ? '' : "l#{location.ref}r#{radius}"
  end

  def filter_hash
    filters = {}
    price_str = price_range_str

    filters['price'] = price_str if price_str
    filters['ad'] = offer_type if offer_type
    filters['price-type'] = price_type if price_type

    return filters
  end

  # replaces spaces with '+'
  def url_keyword
    return keyword.gsub(/ /, '+')
  end

end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_alert, only: [:destroy]

  # GET /alerts
  def index
    @alerts = current_user.alerts
    @user = current_user
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = current_user.alerts.build(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to alerts_url, notice: "Alert \"#{@alert.name}\" created" }
        format.json { render action: 'show', status: :created, location: @alert }
      else
        flash[:alert] = format_errors(@alert)
        format.html { render action: 'new' }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    if @alert
      flash[:notice] = "Alert \"#{@alert.name}\" deleted"
      @alert.destroy

    else
      flash[:alert] = "Alert not found!"
    end

    respond_to do |format|
      format.html { redirect_to alerts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = current_user.alerts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(
        :name, 
        :keyword, 
        :category_id, 
        :min_price, 
        :max_price, 
        :offer_type, 
        :price_type, 
        :location_id, 
        :radius
      )
    end
end

app/views/alerts/index.html.erb
<% @id_placeholder = 999 %>
<script type="text/javascript">
  var _alertIdPlaceholder = '<%= @id_placeholder -%>';
</script>

<div id='main' class='row'>
  <div class='col-md-8 col-md-offset-2'>

    <div class='page-header'>
      <h1>Active Alerts</h1>
    </div>

    <table class='table table-striped'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Keyword</th>
          <th>Category</th>
          <th>Min Price</th>
          <th>Max Price</th>
          <th>Offer Type</th>
          <th>Price Type</th>
          <th>Location</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if @alerts.empty? %>
          <tr>
            <td colspan='9' class='text-center'>
              <h4 id='none-message'>[none]</h4>
            </td>
          </tr>
        <% end %>
        <% @alerts.each do |alert| %>
          <tr>
            <td><%= alert.name %></td>
            <td><%= alert.keyword %></td>
            <td><%= alert.category ? alert.category.name : '' %></td>
            <td><%= number_to_currency(alert.min_price) %></td>
            <td><%= number_to_currency(alert.max_price) %></td>
            <td><%= alert.offer_type_str %></td>
            <td><%= alert.price_type_str %></td>
            <td><%= alert.location_str %></td>
            <td>
              <button class='btn btn-default btn-sm delete-alert-button' data-alert-id='<%= alert.id -%>' data-alert-name='<%= alert.name -%>'>
                <span class='glyphicon glyphicon-remove'></span>
              </button>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <% if @user.can_add_alert? %>
          <tr>
            <td colspan='9'>
              <%= link_to new_alert_path, id: 'new-alert-button', class: 'btn btn-default' do -%>
                <span class='glyphicon glyphicon-plus'></span>
              <% end %>
            </tr>
          </tr>
        <% end %>
      </tfoot>
    </table>

    <h5 id='alert-count' class='text-right'>
      <%= "#{@alerts.count} of #{User::MAX_ALERTS} available alerts" -%>
    </h5>

    <h5>
      Hit the + button to create a new Gumtree alert, or the x button on a row
      to delete a search
    </h5>
    <br />
    <div class='well'>
      <h5>Note:</h5>
      <p>
        Gumtree will be checked every 10 minutes, and an email will only be sent
        if there are any new items.
      </p>
      <p>
        To cancel an alert, return to this page and delete the row.
      </p>
    </div>

  </div>
</div>

<%# Delete confirm modal %>
<div id='confirm-delete-modal' class="modal fade">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body text-center"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <%= button_to 'Ok', alert_path(@id_placeholder), method: :delete, id: 'modal-ok-button', class: 'btn btn-primary' -%>
      </div>
    </div>
  </div>
</div>

app/views/alerts/new.html.erb
<script type="text/javascript">
	var _categories = <%= Category.all.to_json.html_safe -%>;
</script>

<div id='main' class='row'>
  <div class='col-md-8 col-md-offset-2'>

  	<div class='page-header'>
			<h1>New Alert</h1>
		</div>

		<%= form_for @alert, html: { class: 'form-horizontal', role: 'form' } do |f| %>

		  <div class="form-group">
		    <%= f.label :name, class: 'col-sm-2 control-label' %>
		    <div class="col-sm-6">
		    	<%= f.text_field :name, class: 'form-control has-error', required: 'required' %>
	    	</div>
		  </div>

		  <div class="form-group">
		    <%= f.label :keyword, class: 'col-sm-2 control-label' %>
		    <div class="col-sm-6">
		    	<%= f.text_field :keyword, class: 'form-control' %>
	    	</div>
		  </div>

		  <hr />

		  <div class="form-group">
		    <label class='col-sm-2 control-label'>Category</label>
		    <div class="col-sm-3">
		    	<select id='parent-category' class='form-control'></select>
	    	</div>
		    <div class="col-sm-3">
		    	<%= f.select :category_id, [], {}, { id: 'child-category', class: 'form-control' } %>
	    	</div>
		  </div>

		  <hr />

		  <div class="form-group">
		    <label class='col-sm-2 control-label'>Location</label>
		    <div class="col-sm-3">
		    	<select id='state-select' class='form-control'>
		    		<option value=''>All</option>
		    		<% Location.states.each do |state| %>
		    			<option value='<%= state.id -%>'><%= state.name -%></option>
		    		<% end %>
		    	</select>
	    	</div>	    	
		    <div class="col-sm-3">
	    		<%= f.select :radius, Location::RADIUS_KMS.collect {|r| [ "#{r}km", r ]}, { }, { class: 'form-control' } %>
		    </div>
		  </div>

		  <div class='form-group'>		  	
	    	<div class='col-sm-2 col-sm-offset-2'>	    		
		    	<select id='region-select' class='hidden form-control'></select>
	    	</div>
	    	<div class='col-sm-2'>	    		
		    	<select id='area-select' class='hidden form-control'></select>
	    	</div>
	    	<div class='col-sm-2'>	    		
		    	<select id='town-select' class='hidden form-control'></select>
	    	</div>
	    	<%= f.hidden_field :location_id, id: 'location-field' -%>
    	</div>

		  <hr />

		  <div class="form-group">
		    <label class='col-sm-2 control-label'>Price range</label>
		    <div class="col-sm-3">
		    	<div class='input-group'>
		    		<span class="input-group-addon">$</span>
		    		<%= f.text_field :min_price, class: 'form-control', placeholder: 'min' %>
	    		</div>
	    	</div>
		    <div class="col-sm-3">
		    	<div class='input-group'>
		    		<span class="input-group-addon">$</span>
		    		<%= f.text_field :max_price, class: 'form-control', placeholder: 'max' %>
	    		</div>
	    	</div>
		  </div>

		  <div class="form-group">
		    <%= f.label :offer_type, class: 'col-sm-2 control-label' %>
		    <div class="col-sm-6">
		    	<%= f.select :offer_type, Alert::OFFER_TYPES, { include_blank: 'All' }, { class: 'form-control' } %>
	    	</div>
		  </div>

		  <div class="form-group">
		    <%= f.label :price_type, class: 'col-sm-2 control-label' %>
		    <div class="col-sm-6">
		    	<%= f.select :price_type, Alert::PRICE_TYPES, { include_blank: 'All' }, { class: 'form-control' } %>
	    	</div>
		  </div>

		  <div class="form-group">
		  	<div class="col-sm-offset-2 col-sm-6 text-right">
			  	<%= link_to 'Cancel', alerts_path, class: 'btn btn-default' %>
			    <%= f.submit class: 'btn btn-primary' %>
		    </div>
		  </div>

		<% end %>

	</div>
</div>